// Minimal ISO country list with codes, names, and flag emojis.
// Extend as needed. Using ISO 3166-1 alpha-2 codes.

const rawCountries = [
	['AF', 'Afghanistan'],
	['AL', 'Albania'],
	['DZ', 'Algeria'],
	['AR', 'Argentina'],
	['AM', 'Armenia'],
	['AU', 'Australia'],
	['AT', 'Austria'],
	['AZ', 'Azerbaijan'],
	['BH', 'Bahrain'],
	['BD', 'Bangladesh'],
	['BY', 'Belarus'],
	['BE', 'Belgium'],
	['BZ', 'Belize'],
	['BJ', 'Benin'],
	['BO', 'Bolivia'],
	['BA', 'Bosnia and Herzegovina'],
	['BW', 'Botswana'],
	['BR', 'Brazil'],
	['BG', 'Bulgaria'],
	['BF', 'Burkina Faso'],
	['BI', 'Burundi'],
	['KH', 'Cambodia'],
	['CM', 'Cameroon'],
	['CA', 'Canada'],
	['CL', 'Chile'],
	['CN', 'China'],
	['CO', 'Colombia'],
	['CD', 'Congo (DRC)'],
	['CR', 'Costa Rica'],
	['HR', 'Croatia'],
	['CU', 'Cuba'],
	['CY', 'Cyprus'],
	['CZ', 'Czechia'],
	['DK', 'Denmark'],
	['DO', 'Dominican Republic'],
	['EC', 'Ecuador'],
	['EG', 'Egypt'],
	['SV', 'El Salvador'],
	['EE', 'Estonia'],
	['SZ', 'Eswatini'],
	['ET', 'Ethiopia'],
	['FI', 'Finland'],
	['FR', 'France'],
	['GE', 'Georgia'],
	['DE', 'Germany'],
	['GH', 'Ghana'],
	['GR', 'Greece'],
	['GT', 'Guatemala'],
	['HT', 'Haiti'],
	['HN', 'Honduras'],
	['HU', 'Hungary'],
	['IS', 'Iceland'],
	['IN', 'India'],
	['ID', 'Indonesia'],
	['IR', 'Iran'],
	['IE', 'Ireland'],
	['IL', 'Israel'],
	['IT', 'Italy'],
	['JP', 'Japan'],
	['JO', 'Jordan'],
	['KZ', 'Kazakhstan'],
	['KE', 'Kenya'],
	['KR', 'South Korea'],
	['KW', 'Kuwait'],
	['KG', 'Kyrgyzstan'],
	['LV', 'Latvia'],
	['LB', 'Lebanon'],
	['LR', 'Liberia'],
	['LT', 'Lithuania'],
	['LU', 'Luxembourg'],
	['MG', 'Madagascar'],
	['MW', 'Malawi'],
	['MY', 'Malaysia'],
	['ML', 'Mali'],
	['MT', 'Malta'],
	['MX', 'Mexico'],
	['MD', 'Moldova'],
	['MN', 'Mongolia'],
	['ME', 'Montenegro'],
	['MA', 'Morocco'],
	['MZ', 'Mozambique'],
	['NA', 'Namibia'],
	['NP', 'Nepal'],
	['NL', 'Netherlands'],
	['NZ', 'New Zealand'],
	['NI', 'Nicaragua'],
	['NE', 'Niger'],
	['NG', 'Nigeria'],
	['MK', 'North Macedonia'],
	['NO', 'Norway'],
	['OM', 'Oman'],
	['PK', 'Pakistan'],
	['PA', 'Panama'],
	['PY', 'Paraguay'],
	['PE', 'Peru'],
	['PH', 'Philippines'],
	['PL', 'Poland'],
	['PT', 'Portugal'],
	['QA', 'Qatar'],
	['RO', 'Romania'],
	['RU', 'Russia'],
	['RW', 'Rwanda'],
	['SA', 'Saudi Arabia'],
	['SN', 'Senegal'],
	['RS', 'Serbia'],
	['SG', 'Singapore'],
	['SK', 'Slovakia'],
	['SI', 'Slovenia'],
	['ZA', 'South Africa'],
	['ES', 'Spain'],
	['LK', 'Sri Lanka'],
	['SE', 'Sweden'],
	['CH', 'Switzerland'],
	['TW', 'Taiwan'],
	['TZ', 'Tanzania'],
	['TH', 'Thailand'],
	['TG', 'Togo'],
	['TT', 'Trinidad and Tobago'],
	['TN', 'Tunisia'],
	['TR', 'Türkiye'],
	['UG', 'Uganda'],
	['UA', 'Ukraine'],
	['AE', 'United Arab Emirates'],
	['GB', 'United Kingdom'],
	['US', 'United States'],
	['UY', 'Uruguay'],
	['UZ', 'Uzbekistan'],
	['VE', 'Venezuela'],
	['VN', 'Vietnam'],
	['ZM', 'Zambia'],
	['ZW', 'Zimbabwe'],
];

const codeToFlag = (code) =>
	code
		.toUpperCase()
		.split('')
		.map((c) => String.fromCodePoint(127397 + c.charCodeAt(0)))
		.join('');

export const countries = rawCountries.map(([code, name]) => ({
	code,
	name,
	flag: codeToFlag(code),
}));

export const findCountry = (codeOrName) => {
	if (!codeOrName) return null;
	const lc = codeOrName.toLowerCase();
	return countries.find(
		(c) => c.code.toLowerCase() === lc || c.name.toLowerCase() === lc,
	);
};

export default countries;
